services:
  test-db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      TEST_DATABASE_URL: postgres://postgres@test-db:5432/test_db?sslmode=disable
    depends_on:
      test-db:
        condition: service_healthy
    command: ["go", "test", "-v", "./store"]

volumes:
  test-db-data:
